distributed.nanny - INFO -         Start Nanny at: 'tcp://172.16.37.156:40031'
distributed.worker - INFO -       Start worker at:  tcp://172.16.37.156:34049
distributed.worker - INFO -          Listening to:  tcp://172.16.37.156:34049
distributed.worker - INFO -          dashboard at:        172.16.37.156:37625
distributed.worker - INFO - Waiting to connect to:    tcp://172.16.33.2:45818
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                         45
distributed.worker - INFO -                Memory:                  93.13 GiB
distributed.worker - INFO -       Local Directory: /gpfs/work/machnitz/dask_storage/dask-worker-space/worker-h_gwlvf_
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:    tcp://172.16.33.2:45818
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 52 memory: 116 MB fds: 22>>
Traceback (most recent call last):
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/distributed/system_monitor.py", line 96, in update
    gpu_extra = nvml.one_time()
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/distributed/diagnostics/nvml.py", line 45, in one_time
    h = _pynvml_handles()
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/distributed/diagnostics/nvml.py", line 20, in _pynvml_handles
    count = pynvml.nvmlDeviceGetCount()
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/pynvml.py", line 797, in nvmlDeviceGetCount
    fn = _nvmlGetFunctionPointer("nvmlDeviceGetCount_v2")
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/pynvml.py", line 325, in _nvmlGetFunctionPointer
    raise NVMLError(NVML_ERROR_UNINITIALIZED)
pynvml.NVMLError_Uninitialized: Uninitialized
tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 9 memory: 116 MB fds: 23>>
Traceback (most recent call last):
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/distributed/system_monitor.py", line 96, in update
    gpu_extra = nvml.one_time()
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/distributed/diagnostics/nvml.py", line 45, in one_time
    h = _pynvml_handles()
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/distributed/diagnostics/nvml.py", line 20, in _pynvml_handles
    count = pynvml.nvmlDeviceGetCount()
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/pynvml.py", line 797, in nvmlDeviceGetCount
    fn = _nvmlGetFunctionPointer("nvmlDeviceGetCount_v2")
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/pynvml.py", line 325, in _nvmlGetFunctionPointer
    raise NVMLError(NVML_ERROR_UNINITIALIZED)
pynvml.NVMLError_Uninitialized: Uninitialized
tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 4 memory: 117 MB fds: 24>>
Traceback (most recent call last):
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/distributed/system_monitor.py", line 96, in update
    gpu_extra = nvml.one_time()
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/distributed/diagnostics/nvml.py", line 45, in one_time
    h = _pynvml_handles()
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/distributed/diagnostics/nvml.py", line 20, in _pynvml_handles
    count = pynvml.nvmlDeviceGetCount()
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/pynvml.py", line 797, in nvmlDeviceGetCount
    fn = _nvmlGetFunctionPointer("nvmlDeviceGetCount_v2")
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/pynvml.py", line 325, in _nvmlGetFunctionPointer
    raise NVMLError(NVML_ERROR_UNINITIALIZED)
pynvml.NVMLError_Uninitialized: Uninitialized
tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 4 memory: 117 MB fds: 24>>
Traceback (most recent call last):
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/distributed/system_monitor.py", line 96, in update
    gpu_extra = nvml.one_time()
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/distributed/diagnostics/nvml.py", line 45, in one_time
    h = _pynvml_handles()
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/distributed/diagnostics/nvml.py", line 20, in _pynvml_handles
    count = pynvml.nvmlDeviceGetCount()
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/pynvml.py", line 797, in nvmlDeviceGetCount
    fn = _nvmlGetFunctionPointer("nvmlDeviceGetCount_v2")
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/pynvml.py", line 325, in _nvmlGetFunctionPointer
    raise NVMLError(NVML_ERROR_UNINITIALIZED)
pynvml.NVMLError_Uninitialized: Uninitialized
tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 4 memory: 117 MB fds: 24>>
Traceback (most recent call last):
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/distributed/system_monitor.py", line 96, in update
    gpu_extra = nvml.one_time()
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/distributed/diagnostics/nvml.py", line 45, in one_time
    h = _pynvml_handles()
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/distributed/diagnostics/nvml.py", line 20, in _pynvml_handles
    count = pynvml.nvmlDeviceGetCount()
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/pynvml.py", line 797, in nvmlDeviceGetCount
    fn = _nvmlGetFunctionPointer("nvmlDeviceGetCount_v2")
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/pynvml.py", line 325, in _nvmlGetFunctionPointer
    raise NVMLError(NVML_ERROR_UNINITIALIZED)
pynvml.NVMLError_Uninitialized: Uninitialized
tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 2 memory: 117 MB fds: 24>>
Traceback (most recent call last):
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/distributed/system_monitor.py", line 96, in update
    gpu_extra = nvml.one_time()
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/distributed/diagnostics/nvml.py", line 45, in one_time
    h = _pynvml_handles()
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/distributed/diagnostics/nvml.py", line 20, in _pynvml_handles
    count = pynvml.nvmlDeviceGetCount()
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/pynvml.py", line 797, in nvmlDeviceGetCount
    fn = _nvmlGetFunctionPointer("nvmlDeviceGetCount_v2")
  File "/gpfs/home/machnitz/miniconda3/envs/plankton/lib/python3.7/site-packages/pynvml.py", line 325, in _nvmlGetFunctionPointer
    raise NVMLError(NVML_ERROR_UNINITIALIZED)
pynvml.NVMLError_Uninitialized: Uninitialized
distributed.worker - INFO - Stopping worker at tcp://172.16.37.156:34049
distributed.nanny - INFO - Worker closed
slurmstepd: error: *** JOB 524406 ON n156 CANCELLED AT 2021-06-15T09:42:31 ***
slurmstepd: error: task_p_post_term: rmdir(/dev/cpuset/slurm524406/slurm524406.4294967294_0) failed Device or resource busy
